### ISSUE TITLE
Failed to compile application

### ISSUE THREAD

**Issue by EmFl** [ezBadminton/ezBadmintonAdmin#1]
Hello,
I'm trying to run this but I am new to flutter/dart and I can't figure out what's going on here. I've followed your detailed instructions but always end up with the following errors.
Do you have any what could cause this ?
Thank you !
```
Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22631.3155]
Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.129
Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.80
[1]: Windows (windows)
[2]: Chrome (chrome)
[3]: Edge (edge)
Please choose one (or "q" to quit): 2
Launching lib\main.dart on Chrome in debug mode...
../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_numerics-0.0.6/lib/src/precision.dart:16:27: Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 9223372036854775808 is the nearest value that can be represented exactly.
const int int64MaxValue = 9223372036854775807;
                          ^^^^^^^^^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_numerics-0.0.6/lib/src/euclid.dart:86:35: Error: The integer literal 0x07EDD5E59A4E28C2 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 0x7edd5e59a4e28c0 is the nearest value that can be represented exactly.
      ((number - (number >> 1)) * 0x07EDD5E59A4E28C2) >> 58];
                                  ^^^^^^^^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/dart_numerics-0.0.6/lib/src/euclid.dart:86:55: Error: The operator '>>' isn't defined for the class 'num'.
Try correcting the operator to an existing operator, or defining a '>>' operator.
      ((number - (number >> 1)) * 0x07EDD5E59A4E28C2) >> 58];
                                                      ^^
Waiting for connection from debug service on Chrome...             66,5s
Failed to compile application.
```

**Comment by Snonky** [comment]
Hi, thanks for looking into the project!

The app in this repo is intended as a desktop app only. Some dependencies are not compatible with the web platform, those are the errors you are seeing. To compile the app, you would have to select the Windows device.

I will clarify the readme about that, thanks for the hint.

Unrelated but relevant for building the project: I just committed some changes including a change to the DB schema. Please git pull and re-import the [pb_schema.json](https://gist.githubusercontent.com/Snonky/1a596069391fb06eb3d916934e8c140b/raw/pb_schema.json) into your pocketbase.

**Comment by EmFl** [comment]
Thanks for the prompt support !
I initially went with the browser route because I saw that the Microsoft dev tool required 10GB of disk space just to compile the app!
Clearly works better with the desktop target :) I'll test the software during the weekend since there is a tournament :) 
Thanks for this, app like that is surprisingly hard to find.

**Comment by Snonky** [comment]
No problem! Any feedback from your testing is appreciated! I am also open for questions about usage.

I have to insert a word of caution though: The app is not released and still under development, thus there are missing features and it is not guaranteed to run stable. The compilation instructions are targeted at contributors. I'd recommend playing through a mock-tournament to see if the current state of the app matches your needs.
